/**
 * Represents a request to perform an audit on a specified URL.
 *
 * @property url - The URL to be audited. This should be a valid web address that the audit process will analyze.
 * @property use_llm - (Optional) Indicates whether a Large Language Model (LLM) should be used during the audit.
 *                     If set to true, the audit may leverage AI-powered analysis for enhanced insights.
 */
export interface AuditRequest {
  url: string;
  use_llm?: boolean;
}


/**
 * Represents the structured data extracted from a web page.
 * 
 * @property title - The title of the web page.
 * @property meta_description - The meta description of the web page.
 * @property headings - An array of headings extracted from the page.
 * @property image_url - The URL of an image associated with the page.
 */
export interface ExtractedPageData {
  title: string | null;
  meta_description: string | null;
  headings: string[];
  image_url: string | null;
}


/**
 * Represents a recommendation for schema markup on a web page.
 * @property schema_type - The type of schema markup recommended (e.g., Article, Product, Organization).
 * @property rationale - A short explanation or rationale for the recommendation.
 * @property json_ld - The recommended structured data in JSON-LD format.
 * @property source - The source of the recommendation (e.g., LLM, Rule-based).
 */
export interface SchemaRecommendation {
  schema_type: string;
  rationale: string;
  json_ld: Record<string, unknown>;
  source: string;
}


/**
 * Represents debugging information or logs generated by the language model during an audit.
 * 
 * @property llm_enabled - Indicates whether the language model is enabled for the audit.
 * @property llm_used - Indicates whether the language model was used during the audit.
 * @property llm_error - An error message associated with the language model, if any.
 */
export interface LlmDebug {
  llm_enabled: boolean;
  llm_used: boolean;
  llm_error: string | null;
}


/**
 * Represents the response structure for an audit operation.
 *
 * @property url - The URL of the audited web page.
 * @property page_type - The detected type or category of the page (e.g., article, product, homepage).
 * @property geo_summary - A summary of geographic information or findings extracted from the page.
 * @property extracted_data - The structured data extracted from the page, encapsulated in the `ExtractedPageData` type.
 * @property schema_recommendation - Recommendations for schema markup improvements, provided as a `SchemaRecommendation` object.
 * @property llm_debug - Debugging information or logs generated by the language model during the audit, represented by the `LlmDebug` type.
 */
export interface AuditResponse {
  url: string;
  page_type: string;
  geo_summary: string;
  extracted_data: ExtractedPageData;
  schema_recommendation: SchemaRecommendation;
  llm_debug: LlmDebug;
}


/**
 * Represents an error response from the API.
 *
 * @property detail - A human-readable description of the error.
 */
export interface ApiErrorResponse {
  detail: string;
}